name: Deployment
on:
  push:
    branches:
      - main
      - dev
env: 
  MONGODB_DB_NAME: adevdatabasename
jobs:
  test:
    environment: testing
    env:
      # MONGODB_CLUSTER_ADDRESS: cluster0.saknpfe.mongodb.net
      # MONGODB_USERNAME: adatabaseuser
      # MONGODB_PASSWORD: cDkyMnUCKzwtsZhn
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD:  ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_DB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODBDB_USERNAME: ${{ env.MONGODB_USERNAME }}"
